version: '3'
services:
    ssh:
      build: .
      image: build-env
      volumes:
        - ${PWD}/cypress:/weather-checker-tester/cypress
        - ${PWD}/cypress.json:/weather-checker-tester/cypress.json
        # use the node_modules from inside the container and not from local machine
        - /weather-checker-tester/node_modules 
      stdin_open: true
      tty: true
      entrypoint: "/bin/sh"
    tests:
      build: .
      image: build-env
      volumes:
        - ${PWD}/cypress:/weather-checker-tester/cypress
        - ${PWD}/cypress.json:/weather-checker-tester/cypress.json
        # use the node_modules from inside the container and not from local machine
        - /weather-checker-tester/node_modules
      command: npm run cypress:run